# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param r vector of distances associatd with different BEFs
#' @param n_j matrix of integers denoting the start and length of each observations associated BEF distances
#' @param d a 1D grid of positive real values over which the differing intensities are evaluated
#' @param L component truncation number
#' @param K intensity cluster truncation number
#' @param J number of rows in r matrix; number of groups
fhmm_fit <- function(r, n_j, d, L, K, J, iter_max, warm_up, thin, seed, chain, num_posterior_samples) {
    .Call(`_fhmm_fhmm_fit`, r, n_j, d, L, K, J, iter_max, warm_up, thin, seed, chain, num_posterior_samples)
}

